### ISSUE TITLE
OPAM not working

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/ocamhaxe#1]
ATM when using ocamhaxe distrib the opam commandline is not working.
This is discussed here https://github.com/ocaml/opam/issues/2896
Once solved, we need a new fdopen release and also maybe additional config files to modify in Config.hx

**Comment by Simn** [comment]
This is apparently solved in opam 2.2, though I couldn't reproduce it with the fdopen version either. I think we can close this now, in the long run we likely want to move to opam 2.2 anyway and utilize its native Windows support.
