### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/ocamhaxe#10]
```
C:\git\ocamhaxe\haxe>Build.exe
Access is denied.

C:\git\ocamhaxe\haxe>config
Access is denied.
```

I feel like .exe files shouldn't be in repositories anyway.

**Comment by ncannasse** [comment]
That's weird. Are you using cygwin git or git for windows ? Seems like a user rights problem.

**Comment by Simn** [comment]
```
C:\Users\simn>which git
/usr/bin/git

C:\Users\simn>git --version
git version 2.42.1
```

**Comment by ncannasse** [comment]
Yeah you're having cygwin git, I think I always checkout the ocamhaxe repo with TortoiseGit which uses Git-for-Windows regardless of my PATH.

![image](https://github.com/HaxeFoundation/ocamhaxe/assets/1022912/b213fae3-fb88-4d22-add7-47a188a6e605)

**Comment by Simn** [comment]
Interesting, I never knew the git client made a difference here. But yes when I download the file manually it works. I'm fine with that, the only slightly silly thing is that the readme here says to use cygwin git to avoid the prims.c problem.
